openimis-be-core==1.5.0
openimis-be-report==1.5.0
openimis-be-location==1.5.0
openimis-be-medical==1.5.0
openimis-be-medical_pricelist==1.5.0
openimis-be-product==1.5.0
openimis-be-insuree==1.5.0
openimis-be-policy==1.5.0
openimis-be-contribution==1.5.0
openimis-be-payer==1.4.1
openimis-be-payment==1.5.0
openimis-be-claim==1.5.0
openimis-be-claim_batch==1.5.1
openimis-be-tools==1.5.0
openimis-be-dhis2_etl==1.0.0
openimis-be-api_fhir_r4==1.5.1
openimis-be-calculation==1.5.0
openimis-be-contribution-plan==1.5.0
openimis-be-policyholder==1.5.0
openimis-be-contract==1.5.0
openimis-be-invoice==1.5.0
openimis-be-calcrule-contribution-legacy==1.4.2
openimis-be-calcrule-third_party_payment==1.5.0
openimis-be-calcrule-capitation_payment==1.5.0
openimis-be-calcrule_commission==1.4.2
openimis-be-calcrule_fees==1.4.1
openimis-be-calcrule_unconditional_cash_payment==1.4.1
../openimis-be-csu_py
../openimis-be-program_py
